NixOS/mobile-nixos

default.nix
Exposes the nixos config attribute, and gets device from an
environment variable if not provided as a function argument.
=> default.nix: convenience improvements

modules/initrd-fbterm.nix, modules/module-list.nix
Requires a cross-compilation fix for fbterm (nixos/nixpkgs#72107).
This may stop the display-manager from starting correctly, I think it
prevents X from automatically switching to the correct vt. Requires
some further investigation :)
=> initrd: add fbterm module

lib/image-builder/makeMBR.nix
The size wasn't fixed after aligning the result, this dividing the sizes
by as the alignment.
See the `sizeFragment` for comparison of the bashy maths.
=> imageBuilder.makeMBR: Fixes bug with gap

overlay/make_ext4fs/0001-LEDE-We-need-to-set-EXT4_BG_INODE_ZEROED-on-at-least.patch, overlay/make_ext4fs/default.nix
This may trip newer kernels, under some unknown circumstances.
As shown here:
```
[   10.016001] c7    604 EXT4-fs error (device sda45): ext4_has_uninit_itable:2895: comm mount: Inode table for bg 0 marked as needing zeroing
```
This happens with the google-walleye device, and unvalidated due to
lack of logs, might be affecting xiaomi-lavender
* * *
Provenance information:
This patch comes from the OpenWRT forum.
* https://forum.openwrt.org/t/read-only-file-system-after-a-fresh-installation-of-lede-17-01-5/17242/8
=> make_ext4fs: Fix issue with read-only filesystems

devices/google-marlin/kernel/0001-Revert-four-tty-related-commits.patch, devices/google-marlin/kernel/default.nix
Without this kernel patch to revert these commits, the kernel hangs immediately with no serial port output. My earlier testing was apparently incorrect. I was unknowingly booting with CONFIG_VT disabled. Maybe I tested against the wrong branch or something.
The patch for google-walleye does not apply cleanly, so a new patch was made by matching the commit messages of samueldr's reverts for google-walleye with the corresponding commits in
google-marlin.
With this patch, the configuration under `examples/demo` now boots to xfce, with working touchscreen:
=> google-marlin: Fix CONFIG_VT

examples/demo/configuration.nix
There is one big caveat: When the session fails, the user is thrown back at lightdm, rather than the session restarting.
This is a problem that has to be solved in the future. If we want to use X11, we need to allow the user to log-in from the display manager, rather than rely on an unsafe password-less X11 session. Though, non-X11 session types will not have this issue.
=> demo: Rely on lightdm now that SLiM is gone

modules/initrd-devices.nix, modules/initrd-growpart.nix, modules/module-list.nix, systems/rootfs.nix
With this, the rootfs will expand to the size of the partition it is written on.
Note: NO `fdisk` or similar partitioning tool is being used. This is **only** a dumb "resize to the partition size" operation. This should be safe on all targets.
One issue, though, is that this is **always** being done on boot, using this initrd method.
This probably should rather be done in an installer. This is especially relevant considering that stage-1 is not being updated with rebuilds currently.
=> Allow rootfs to expand to the backing partition

devices/qemu-x86_64/default.nix, modules/system-types/kernel-initrd.nix, overlay/overlay.nix, overlay/seabios/0001-HACK-Adds-mobile-like-VGA-modes.patch, overlay/seabios/default.nix
Quick fixes:
* Fixes issue with missing modules for input (keyboard/mouse)
* Increases RAM
* Attaches the serial console properly to stdin/stdout
* Attaches absolute input
Additionally:
This adds a custom VGA BIOS build that is adding a vertical resolution. This, in turn, better emulates how a device acts.
Tip: Use the "View" menu, and select "Zoom to fit", this will allow you to resize the window.
=> Enhance QEMU device

overlay/adbd/default.nix, overlay/libhybris/0001-HACK-Rely-on-legacy-properties-rather-than-native-pr.patch, overlay/libhybris/0001-Removes-failing-test-for-wayland-less-builds.patch, overlay/libhybris/default.nix
Two big things
* Upgrades libhybris to its latest version
* Fixes issue with adbd with newer libhybris
The main issue with adbd (better described in commit messages and the patch) is that new versions of libhybris highly assume that you will be using libhybris with vendor libraries available.
This is not true here, and especially not with adbd in stage-1.
The adb daemon was running quite fine with the few bits of libhybris it was using, before they changed the behaviour. The added patch reverts the new behaviour to the older behaviour, which makes libhybris not load any libraries for adbd.
In the future, it might be ideal to extract the minimum libhybris required to run adbd, and rely on that instead.
* * *
This does mean that #30 will conflict, I'll rebase it on top of this PR.
=> libhybris: 2018-06-18 -> 2019-12-02

devices/google-walleye/default.nix
It looks like *not* having `quiet` in the kernel cmdline somehow makes
the early init of the framebuffer fail.
I don't know the exact difference, but lowering loglevel rather than
using quiet doesn't work here.
In addition, this splits up the cmdline as a list.
=> google-walleye: Fix early framebuffer

devices/xiaomi-lavender/default.nix, modules/system-types/android.nix
It will install to both A/B slots, and to the boot, and recovery partitions.
To be used like so:
```
$ nix-build --argstr device google-walleye -A build.android-device
$ result/flash-critical.sh
```
This is not documented as being "the way" to install on devices yet since this is almost unusable as it is right now.
The `android-device` output assumes a `rootfs` can be built. The current defaults cannot build a usable rootfs when cross-compiling.
This can be worked around like so:
`local.nix`
```
{ lib, pkgs, ... }:
{
system.build.rootfs = (pkgs.runCommandNoCC "dummy-rootfs" {
passthru = {
filename = "dummy.img";
};
} ''
mkdir -p $out/
touch $out/dummy.img
'');
}
```
Though, this points to a wart: this does not use `lib.mkForce`  or anything similar. Using `lib.mkForce` seemingly does not …
=> Add installer script to android device output

modules/initrd.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/lvgui.nix
This adds the necessary support to better handle other pointing-type
inputs.
* Cursor for non-touch devices
* Handle abs min/max
* Handle touchpads
With this, a tablet-type input, like used by QEMU, now works.
This is important for non-touch uses. It seems antithetical to "Mobile" NixOS, but it's not. The whole boot chain should be dogfood-able on any device NixOS runs. Not all of them have touchscreens.
~~Though, with that said, an improvement could be made with the cursor. The main one would be to use a circle "touch zone" cursor. The way LVGL handles cursors it's not possible, as it assumes `[0, 0]` on the object given as a cursor is the pointy bit of the pointer. A non LVGL-native handling of the cursor will be needed. This would, in turn, gives us the benefit of being able to …
=> Update lvgui for better pointer support

modules/initrd.nix
This can be used to sift through the files in stage-1, and hopefully
pare it down when it bloats.
=> initrd: Add `initrd-meta` build output, with ncdu metadata

modules/cross-workarounds.nix, modules/module-list.nix
With this, we can build disk images with a rootfs with cross-compilation.
They are *not* useful rootfs! They simply compile!
A future upgrade to this will be to make an example system (in the examples folder) which starts a hardware testing LVGUI "applet".
For now, this is enough to make the upcoming hydra builds happy.
=> Add workarounds to enable minimal rootfs cross-compilation.

overlay/libhybris/default.nix
This Nixpkgs commit introduced the breaking change:
* https://github.com/NixOS/nixpkgs/commit/e1831ebea3bcb415800a74fe458f802e63549e1c
`libsupc++.a` is not where it was previously.
=> Fix libhybris regression following gcc target-specific libraries split

lib/eval-config.nix, modules/initrd.nix
Though with *our* modules.
With https://github.com/NixOS/nixpkgs/pull/82960 this fixes the regression from https://github.com/NixOS/nixpkgs/pull/82751.
=> lib/eval-config.nix: Directly use the upstream one

bin/kernel-normalize-config, bin/menuconfig, doc/porting-guide.adoc, overlay/mobile-nixos/kernel/builder.nix
Had an epiphany about ways to co-opt the binary from out of a source tree.
* * *
Fixes #108
=> Add `bin/menuconfig` to configure kernels

devices/google-marlin/default.nix
this phone uses a/b partitions and has a vendor partition, so we should load from them
based on google-walleye config
=> google-marlin: fix partitions

.ci/instantiate-all.nix, .github/workflows/ci.yml, modules/system-types.nix, modules/system-types/u-boot.nix, release.nix
We can expand for more serious work later.
This
* Validates all nix files are parsable.
* Builds the documentation.
* Instantiates everything from release.nix.
The built documentation is also available as an artifact in the checks, as a zip, look at the top right corner. Though, not as useful as if it was directly consumable and uploaded somewhere :(.
* * *
This also fixes two semi-related issues.
* Something with the `nix-env` based eval triggered a behaviour from the system eval that didn't work the same way as on Hydra. This is fixed by having the "none" system type.
* The Pinephone change had a broken eval! This PR would have shown that easily!
=> Add GitHub actions for simple validations

default.nix, lib/image-builder/makeFilesystem.nix, modules/internal.nix, modules/module-list.nix, release.nix, systems/rootfs.nix
This will ensure Hydra builds everything required for the rootfs, making sure our demo rootfs keeps being buildable.
This will also provide a trustable source for the rootfs so end-users can use a somewhat usable system on their device even if they do not have a native aarch64-linux system to build from.
Once merged:
* Add `inNixOSHydra` `true` to the jobset.
* * *
The rootfs goes from 3.3GiB uncompressed to... 798MiB compressed! What a deal!
=> Add the demo rootfs build to release.nix

modules/initrd-vendor.nix
For `google-marlin`, at least.
=> initrd-vendor: mount vendor read-only

README.adoc, default.nix, doc/_support/common.inc, doc/_support/converter/.gitignore, doc/_support/converter/Gemfile, doc/_support/converter/Gemfile.lock, doc/_support/converter/gemset.nix, doc/_support/header.erb, doc/_support/options/default.nix, doc/_support/options/generate-options-listing.rb, doc/_support/styles/index.less, doc/_support/styles/rouge.less, doc/_support/styles/theme.less, doc/default.nix, doc/getting-started.adoc, doc/in-depth/android/partitions.adoc, doc/resources.adoc, lib/eval-config.nix, lib/release-tools.nix, modules/_nixos-integration.nix, modules/initrd-ssh.nix, modules/module-list.nix, modules/quirks/qualcomm/framebuffer.nix, modules/system-types/depthcharge/device-notes.adoc.erb
This adds the options listing to the documentation.
This also reviews how modules are being handled a bit, but in the end it ended up not working like I wanted. Those changes are, thus, mostly useless, but were kept anyway. At least it clearly delineates the NixOS integration.
* * *
Added to the documentation:
* Note about using a pre-built rootfs image
Upcoming:
* ~~Documentation for integration in the system configuration~~ Coming in another PR.
=> doc: Add options listing and other fixes

.ci/instantiate-all.nix, default.nix
Look at this eval:
* https://hydra.nixos.org/eval/1580432#tabs-new
11 New jobs, 11 Removed jobs... Uh oh.
The explanation is in the System column.
Woopsie!
The change in the CI instantiation should prevent this from happening again in the future.
=> Fix evaluation failure where aarch64-linux outputs are accidentally x86_64-linux

devices/oneplus-oneplus3/default.nix, devices/oneplus-oneplus3/kernel/0001-oneplus3-Configure-LEDs-using-kernel-triggers.patch, devices/oneplus-oneplus3/kernel/default.nix, modules/quirks/qualcomm/default.nix, modules/quirks/qualcomm/msm-dwc3-otg_switch-task.rb, modules/quirks/qualcomm/msm-dwc3.nix
Off the heels of #126, I started working on oneplus-oneplus3 polishing to figure out Wi-Fi.
The Wi-Fi efforts for now are on pause, but there is some polishing included here that is useful to upstream right now.
This closes #45 as it is functionally equivalent for stage-2 systems, ~~**but** with one caveat, there is no stage-1 task implemented yet here to do the equivalent.~~
Does the LED thing apply to all oneplus3 models? What about the 3T? The device tree files in the repo are confusing.
=> oneplus-oneplus3: Minor polishing

modules/cross-workarounds.nix
From https://hydra.nixos.org/eval/1581751
1580f35dfbb29a00dbf06110cf31824637ee8635 accidentally introduced udisks in the build.
A local test build of the default "dummy" system disk image wasn't done, thus the failure not found.
=> cross-workarounds: Disable udisks for cross-builds

CONTRIBUTING.adoc, doc/default.nix, doc/getting-started.adoc
Implementation details time!
This uses the CONTRIBUTING.adoc well-known path, so GitHub intrinsically *knows* about the contributing guide.
This is why there are conditionals in the docs to link it up properly. We *are* moving things around when building the docs.
This also serves as a proof-of-concept to reduce the duplication of places to find information. That document ends up being a completely standard page of the site.
=> doc: Add contributing notes

LICENSE, README.adoc, doc/_support/styles/asciidoc-fixes.less, doc/_support/styles/asciidoc.less, doc/about.adoc, doc/default.nix
I feel this should have been done the moment documentation was added, and the project was adopted into the NixOS org.
The README:
* now refers to the documentation, rather than keep instructions that may change
* includes the same kind of content as the main Nixpkgs README
* looks more like the main Nixpkgs README
The main goal is to deduplicate instructions. I don't want to maintain that 2-minutes startup guide, especially considering it's assuming way too much. The *getting started* section **is** what it should have been.
By doing so, we now gained an *about* page, which can be furnished a bit more later, with e.g. #69.
Fixes #73.
=> README: revise README, appearance and content

boot/error/main.rb, boot/gui/main.rb, boot/gui/simulator.nix, boot/init/default.nix, boot/splash/main.rb, modules/initrd-boot-gui.nix, modules/initrd.nix, overlay/mruby-builder/mrbgems/default.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/default.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/lvgui.nix, overlay/mruby-builder/mruby/builder.nix, overlay/mruby-builder/mruby/default.nix
This is a mostly transparent change.
This uses the updated `mruby-lvgui` that uses `mruby-fiddle`, which uses `libffi` rather than writing bespoke bindings for LVGL.
Why make this change if it changes nothing? To reduce the surface of mistakes. I am not a C developer. Probably always be uneasy writing C. Some bits of the bindings already were iffy.
The only bit I'm not happy with, but I am satisfied with, is the struct bindings. Fiddle does not have a way to describe nested structs. (Neither does the ruby mainline Fiddle.) LVGL uses nested structs for styles. To work around the issue, accessor functions in C have been generated. It's not *clean*, but it's working in a correct manner, which for the best.
It already was an issue with the previous bindings, and still is with the Fiddle-based …
=> boot/gui: Use libffi rather than bespoke bindings

devices/asus-dumo/default.nix, devices/asus-flo/default.nix, devices/asus-z00t/default.nix, devices/google-marlin/default.nix, devices/google-walleye/default.nix, devices/motorola-addison/default.nix, devices/oneplus-oneplus3/default.nix, devices/pine64-pinephone-braveheart/default.nix, devices/qemu-x86_64/default.nix, devices/xiaomi-lavender/default.nix, devices/xiaomi-tissot/default.nix, lib/release-tools.nix, modules/devices-metadata.nix, modules/initrd-kernel.nix, modules/initrd-usb.nix, modules/initrd-vendor.nix, modules/initrd.nix, modules/mobile-device.nix, modules/system-types/android/bootimg.nix, modules/system-types/android/default.nix, modules/system-types/depthcharge/default.nix, modules/system-types/depthcharge/depthcharge-build.nix, modules/system-types/qemu-startscript/default.nix, modules/system-types/qemu-startscript/qemu-startscript-build.nix, modules/system-types/u-boot/default.nix
Rather, remove unused options, and then add proper options or use existing NixOS options.
* * *
This gives us working `boot.kernelParams` support for stage-1 builds. Configuration can now add and remove to the kernel parameters.
This also reduces the risks of doing something wrong with the untyped mess of options that was present previously.
=> Remove messy `device.info` option

modules/initrd-usb.nix
See the kernel documentation for configuring gadgets for more details.
https://www.kernel.org/doc/Documentation/usb/gadget_configfs.txt
=> initrd-usb: provide modules required for gadgets in initrd

bin/menuconfig
This wasn't caused by the CI as this is not evaluated using nix expressions part of what the CI checks.
=> bin/menuconfig: Fix breakage caused by #152

devices/motorola-addison/default.nix, modules/quirks/qualcomm/default.nix, modules/quirks/qualcomm/msm-fb-notify-task.rb, modules/quirks/qualcomm/msm-fb-notify.nix
Quite simply, `motorola-addison`'s touch input will not work if the display has not been properly "awakened".
Touching `.../blank` ends up causing `fb_notifier_call_chain` to be called, which ends up causing `rmi4_data->panel_nb.notifier_call` to be called, causing `synaptics_dsx_panel_cb` to be called. This, finally, puts the touch panel active. (`grep` the vendor kernel tree for those names.)
* * *
X11 touch input was working fine. It must be doing things *just right* to wake up the framebuffer. LVGL does not, which means the boot GUI did not work.
=> Add "fb notify" quirk, fixing motorola-addison touch with boot GUI

devices/asus-dumo/default.nix, devices/asus-dumo/firmware/default.nix, modules/initrd-firmware.nix, modules/initrd.nix, modules/module-list.nix
This adds proper support for adding firmware into stage-1.
This PR also adds an example usage of this with `asus-dumo`.
When providing firmware for use during stage-1, pare down the set as much as sensible for your device!
=> Add firmware support to stage-1

overlay/mruby-builder/mrbgems/default.nix
Well, the build wasn't good either with cross, but no tests ran, so it wasn't caught.
See: https://github.com/appPlant/mruby-os/pull/1
* * *
cc @masipcat 
Turns out that part never built on aarch64 native, probably. At least, it never *checked*.
=> mruby-os: Fix native ARM build

devices/pine64-pinephone-braveheart/default.nix, devices/pine64-pinephone-braveheart/firmware/default.nix
The firmware is limited to bluetooth only, nothing else (for now)
requires a discrete firmware file.
It looks like the touchscreen can get one, but it is not required, and
seemingly no one provides one.
* * *
cc @masipcat
This was tested on top of `master`.
Note that since it's unfree, even though it's redistributable, it's not part of the default configuration. (I'll need to consult to know what to do about unfree redistributable).
For now, you'll need to build the initrd using the following config:
```
{ config, ... }:
{
mobile.boot.stage-1.firmware = [
config.mobile.device.firmware
];
}
```
It can also, and probably also should, be added to `hardware.firmware` (the same way).
* * *
What was done:
Using `examples/demo`, verified it could pair with a bluetooth headset.
It wasn't verified …
=> pine64-pinephone-braveheart: Add firmware package

README.adoc
The conditional it so work around an issue where one-line admonitions in GitHub are ugly.
This README is *mainly* for consumption on GitHub.
Should help prevent against #166 or similar.
#168 would be an actual *solution* rather than documentation.
=> README: Add note about unstable branch

doc/in-depth/devices.adoc
As [reported by `Ox4A6F` on IRC](https://logs.nix.samueldr.com/nixos-aarch64/2020-06-18#3624522;).
=> doc: Fix 404 in in-depth devices doc

boot/gui/default.nix
Turns out that `mruby`'s require looks at the actual file name (not the
link) when deciding between loading bytecode or ruby code.
Cross-compilation appends the system to derivation names.
Fun ensues.
This fixes the issue by using `runCommand`, for which it doesn't happen.
* * *
Why didn't I catch this? I tested with QEMU! Native compilation!
=> boot/gui: Fix cross-compilation breakage

overlay/mruby-builder/mrbgems/mruby-lvgui/lvgui.nix, overlay/mruby-builder/mruby/default.nix
The way Nixpkgs handles `pkg-config` during cross is by now using a prefixed binary name.
Many tools are not ready for such a thing, here I am fixing the Mobile NixOS specific issues.
Tested against Nixpkgs b3251e04ee470c20f81e75d5a6080ba92dc7ed3f, which currently fail.
Note that this breaks compatibility with Nixpkgs before that pkg-config change.
Fixes #176
@ingenieroariel, can you confirm that, at least on b3251e04ee470c20f81e75d5a6080ba92dc7ed3f, things work, and also that the changes look okay? Thanks!
=> Fix Mobile NixOS regressions after the pkg-config changes in Nixpkgs

modules/initrd-kernel.nix
The upstream NixOS make-initrd doesn't handle multiple content linking
to the same location.
This fixes a regression introduced in #158 affecting the QEMU VM build, by using the feature added in that PR.
=> initrd: Provide firmwares through the specific option

doc/_support/options/default.nix
Actual work should be done to figure out why those `default = pkgs.___`
cause issues *only* with our docs generation, and don't fail the NixOS
channels :/
I'm fast-tracking this work-around instead of (#181) understanding the problem since the site can't update, so I can't push the news update.
=> doc: Workaround new failure on unstable

overlay/mobile-nixos/kernel/builder.nix
This works around an issue with upstream Nixpkgs and the way pkg-config
is now (admitedly rightly so) prefixed.
In actuality, the kernel build should be fixed upstream, but this would
be a non-trivial thing to get into the kernel.
This was verified with:
* pine64-pinephone-braveheart
* asus-dumo
* asus-z00t (should be a no-op)
* motorola-addison (should be a no-op)
cc @s1ng0c
=> kernel-builder/menuconfig: Use pkg-config wrapper

bin/menuconfig, default.nix, lib/release-tools.nix, modules/system-types/u-boot/default.nix
Thus, facilitating external devices development.
See my [mobile-nixos-extra-devices](https://github.com/samueldr/mobile-nixos-extra-devices) for an example usage.
**NOTE:** This is *not* intended to create a rift where users need to make their devices external to this repository. Oh no, this is only intended to allow working with what shouldn't be in this repo. If you look at my example repo, this is used for a pinebook pro, which is definitely not a mobile device for this repo :).
* * *
This also fixes a small oversight in the u-boot system, where an option that should have been made optional was mandatory.
* * *
=> Allow passing device definitions by path

modules/initrd.nix
See Nixpkgs d3a991d41028c5d2a5af2796c0bb542836457822
Fixes issues from https://hydra.nixos.org/eval/1602690
=> initrd: Fix for lvm2 multiple output

lib/release-tools.nix, modules/_nixos-disintegration/default.nix
Two distinct issues:
* * *
The option has been removed.
https://github.com/NixOS/nixpkgs/commit/aebf9a4709215c230e5841d60e2bce6aa6627ac8
* * *
Using an removed option, now detected due to stricter checking in the modules system.
=> Fix regressions coming from Nixpkgs upgrades

modules/initrd.nix
Mirrors https://github.com/NixOS/nixpkgs/commit/7361f6f25266e8bc104f9bafaec860e67ea45c65
Tested with pinephone: now boots to graphical "Mobile NixOS" splash on screen / login prompt on serial.
=> initrd: handle systemd-udevd being a symlink to udevadm

overlay/mobile-nixos/kernel/builder.nix
This is going to be annoying for "end-users" (developers), but this is going to be much more helpful in the end. You **know** the actual configuration shown is in use, no default answers changing anything.
This is a draft because:
=> kernel-builder: Force configuration to be normalized

doc/_support/options/default.nix, doc/pkgs.nix
The documentation could get stuck building from under our feet at any point a new option used the following form when defining an option default value.
```
default = "${pkgs.hello}";
```
* * *
"default" values in Nixpkgs manual can *somehow* be escaped by the
documentation back to their original string form.
The following ends up escaped into the manual as `"${pkgs.hello}"`.
```
default = "${pkgs.hello}";
```
The methods for this magic have not been found.
Instead, we just change the default strict `handleEvalIssue` so that it
does absolutely nothing and lets them through.
Anyway we won't be building them.
=> Fix docs regression, and removes workarounds

devices/asus-flo/kernel/default.nix, doc/in-depth/kernel-builder.adoc, overlay/mobile-nixos/kernel/builder.nix
It looks like this is not a regression from the latest changes to the kernel builder. Testing on top of ffdba8fecbb2aee6fb79e4a1cde5e06035ef407b exhibits the same issue.
This change works around the issue by doing it with one invocation of `make`, rather than doing it twice.
It has not been figured out at which exact version of the kernel this stops being an issue, and if it is an issue from mainline Linux outright, or something that came from Android-specific modifications.
Though it has been verified that for 3.18, both Qualcomm and Mediatek source trees exhibit the same issue.
Fixes #216
* * *
=> kernel-builder: Work around kernels getting compiled two times

overlay/mruby-builder/mrbgems/mruby-lvgui/default.nix
This update makes the HAL compatible with the mainline naming scheme for batteries under sysfs. This, in turn, makes the battery status work on the Pinephone.
=> mruby-lvgui: update with latest changes to battery HAL

examples/demo/configuration.nix
Notable changes:
* Added `dtc` to the build, since `dtc /proc/device-tree` is helpful.
* Fixed the upstream renamed options
=> Misc. updates to the examples/demo system

devices/pine64-pinephone/u-boot/default.nix, lib/image-builder/makeGPT.nix, modules/system-types/u-boot/default.nix
This is how it should have been done from the beginning.
What this gives us:
* Ability to make more than 4 partitions.
* Somewhat shield the Allwinner bootloader
* Partition labels
We don't really need more than 4 partitions. Though now we have the ability for it. We would need it if we were able to put the Allwinner bootloader at a location inside the usable space.
Though, shielding the bootloader from haphazard partitioning is nice.
Finally, partition labels are not strictly needed; we were doing just fine without. But this is more what I had in mind originally for a well-designed system.
They're partitions that are going to be used basically like the Android-common ones.
The `misc` partition is a mebibyte of bytes that can be used for dialoguing from system to bootloader to system. …
=> system-types/u-boot: Use GPT for partitions + add partitions

boot/gui/main.rb, examples/hello/app/windows/quit.rb, modules/hardware.nix, modules/initrd.nix, modules/module-list.nix, modules/system-types/android/default.nix
This adds a "HAL" options layer where we can describe some hardware-specific abstractions.
The only one implemented for now is the reboot modes list.
This list is interpreted by the boot GUI in an implementation-defined way. All of the implementation details are internal and could change at any time for now.
The goal is to make sure that, e.g. on the Pinephone, the reboot options that don't apply are not present.
=> Boot GUI: only show relevant reboot options

boot/init/lib/mounting.rb, boot/init/lib/progress.rb, boot/init/lib/system.rb, boot/init/lib/task.rb, boot/init/tasks/auto_resize.rb, boot/init/tasks/luks.rb, boot/init/tasks/splash.rb, boot/splash/lib/keyboard.rb, boot/splash/lib/progress_bar.rb, boot/splash/lib/text_area.rb, boot/splash/lib/ui.rb, boot/splash/main.rb, examples/testing/README.md, examples/testing/qemu-cryptsetup/README.md, examples/testing/qemu-cryptsetup/configuration.nix, examples/testing/qemu-cryptsetup/default.nix, modules/generated-filesystems.nix, modules/luks.nix, modules/module-list.nix, overlay/lib/extra-utils.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/default.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/lvgui.nix
*This builds upon #233, soon-to-be merged.*
* * *
This adds the required facilities for asking for the passphrase during the boot progress tracking
In addition to a test system made specifically to test that the unlocking works.
Note that there is **no** automatic way to get encryption going on your device yet. This is for something further along. For the time being, you will have to manually configure your stage-1 to know about the cryptsetup setup for your device. In addition, you will have to handle `cryptsetup reencrypt` yourself on your device. (Check the testing system, there may be clues, e.g. using 32MB for resize.)
I will, at some point, add documentation about manually encrypting a device, but that will happen once I have done it and tested it. Though the steps are quite …
=> stage-1: Add interactive LUKS decrypting

boot/init/lib/dependencies.rb, boot/init/lib/progress.rb, boot/init/lib/system.rb, boot/init/lib/task.rb, boot/init/tasks/auto_resize.rb, boot/init/tasks/luks.rb, boot/init/tasks/mount.rb, boot/init/tasks/splash.rb, doc/in-depth/stage-1.adoc
*This builds on #234*
* * *
With this PR, the boot is aborted when no tasks can be run for a given amount of time.
The test case I used for this is to produce the `demo` image with a bad `filesystems."/".device`.
```diff
diff --git a/modules/rootfs.nix b/modules/rootfs.nix
index ff491e2c998f..7bf93a9526d2 100644
--- a/modules/rootfs.nix
+++ b/modules/rootfs.nix
@@ -78,7 +78,7 @@ in
fileSystems = {
"/" = lib.mkDefault {
-      device = "/dev/disk/by-label/${rootfsLabel}";
+      device = "/dev/disk/by-label/${rootfsLabel}_FAIL";
fsType = "ext4";
autoResize = true;
};
```
This is representative enough of someone not flashing the rootfs on their device.
The user experience is as follows:
- When in the situation of *hanging*, a message is shown on the progress display.
- When it fails, the …
=> stage-1: Detect hung tasks and abort boot

.github/workflows/ci.yml
The actions stopped working due to a GitHub-side regression/deprecation.
=> ci: Update dependencies

devices/xiaomi-begonia/kernel/default.nix
While discussing with other devs, working on a samsung device on another
distro, I figured out it was basically free to try and build it with a
shim that's calling "proper" `dtc` and see if it works.
It worked for xiaomi-begonia.
It worked for that other device (on postmarketOS) too!
This means we're suddently gaining the ability to build natively.
Additionally, for postmarketOS, it allows them to build, considering
`dtc_overlay` uses glibc, and postmarketOS doesn't.
=> xiaomi-begonia: Don't rely on bundled dtc_overlay

boot/splash/lib/ui.rb, modules/initrd-boot-gui.nix, modules/initrd.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/default.nix, overlay/mruby-builder/mrbgems/mruby-lvgui/lvgui.nix
With this change set, the physical keyboard can be used to input passphrases and such.
Note that this is currently hardcoded to the "us" keyboard, only because other layouts are expected to be implemented in unison with locale-aware on-screen keyboard. The irony is not lost on me, a non-"us" keyboard user implementing the "us" keyboard only.
In fact, the on-screen keyboard will be able to re-use xkbcommon's knowledge of keyboard layouts! Much better than re-implementing it all!
See, we'll simply build the keyboard from return values of the scancodes at their expected locations! We should even be able to support "3rd layer" (alt gr) this way in a trivial manner.
So let's not keep this improvement from landing, while the internationalized keyboard issue is scheduled to be handled at a later …
=> stage-1: Handle (physical) keyboard input

devices/sony-pioneer/README.adoc
In some cases, you cannot flash a new firmware when using a USB3 cable.
=> Solution for USB3 flashing issue

overlay/mruby-builder/mruby/builder.nix
Tested with:
```
$ nix-build --argstr device qemu-x86_64 -A pkgs.hello-mruby
```
=> mruby-builder: Fix `passthru` being required for mruby builder

boot/init/tasks/luks.rb
This means that we shouldn't raise an exception, but rather fail outright. The background being black means that things *failed successfully*, as expected.
The big difference here is how the error will be shown.
Rather than being treated as things failing to run as expected from the `init` code, things fail with a really specific error message, about how it failed to unlock.
=> boot: LUKS errors are "controlled"

overlay/mobile-nixos/kernel/builder.nix
This config currently breaks the build for native aarch64 pinephone
kernel builds, as it does not appear with cross-compilation.
=> kernel-builder: Strip another troublesome config

devices/razer-cheryl2/default.nix
This change does not fix anything, it was some cleanup that was made while testing stage-0 with the device.
Stage-0 didn't work, but this fix is good still. Let's not waste some good code.
=> razer-cheryl2: Workaround made more descriptive

overlay/mobile-nixos/kernel/builder.nix
It seems that under specific conditions:
- 2a5 hardware
- -j22
the call to `make install zinstall` (simplified here) may break, with
the installation of `System.map` happening in a manner where it fails
the build. It was not trivial to reproduce elsewhere than on a 2a5
machine, for unknown reasons.
It was also only observed on google-walleye, but there is no reason is
shouldn't be failing on other devices too.
Odd.
* * *
More details:
- https://logs.nix.samueldr.com/nixos-dev/2020-12-30#1609366884-1609368903;
- https://logs.nix.samueldr.com/nixos-dev/2020-12-31#1609375219-1609376210;
=> kernel-builder: Call either of install or zinstall

modules/initrd-kernel.nix
The update from 29a10085f313904516992684f1d0fd647fb2ad6d caused the
uncompressed kernel to not be installed anymore into the kernel output.
This meant that building the top-level argument failed as a file assumed
to exist wasn't there anymore.
We now provide the appropriate filename when we know it.
=> fix build failure by providing kernel filename to internal NixOS option

boot/init/lib/system.rb, boot/init/tasks/switch_root.rb, modules/stage-1/tasks/usb-gadget-task.rb
Fixes an issue where the USB controller is in a confusing state for the freshly booting kernel.
This adds a specialized code path into the kexec code path, but it's better than making the wrong abstraction.
We, *anyway* need to work on generic teardown later on.
Tested on an out-of-tree device.
=> stage-0: Teardown gadget before kexec

devices/uefi-x86_64/default.nix
This, in turn, causes the kernel to go to console level 4. Not ideal
when a user tries to set it to something else. Leave this to
boot.consoleLogLevel.
=> uefi-x86_64: Drop "quiet" kernel command line option

boot/init/tasks/switch_root.rb
Those errors are non-issues.
Tear-down should, anyway, be implemented in a library to be used in
other tools like target disk mode and a stage-2 gadget utility.
=> boot/init: Work around gadget teardown errors

boot/init/tasks/graphics.rb, boot/lib/lvgui/lvgl/ffi.rb, boot/lib/lvgui/lvgl/introspection.rb, boot/lib/lvgui/lvgl/lvgl.rb, boot/lib/lvgui/lvgui/base_window.rb, boot/lib/lvgui/lvgui/gui.rb, boot/lib/lvgui/lvgui/option_selection.rb, boot/lib/lvgui/lvgui/switch_line.rb, boot/lib/lvgui/lvgui/windows.rb, boot/script-loader/mruby-lvgui-native-fragment/lvgui.nix, examples/hello/app/main.rb, examples/hello/app/windows/display_validation.rb, examples/hello/app/windows/lvguitesting.rb, examples/hello/app/windows/main.rb, examples/hello/configuration.nix, examples/target-disk-mode/app/simulator.nix, examples/target-disk-mode/app/windows/main.rb
First, to the lvgui project itself:
- Support `libinput` as an input source
- Try `DRM` before falling back to `fbdev`
Then, in LVGUI
- Added a *toggle switch* control
- Added an *select* control
Compared to `evdev`, really there shouldn't be any differences. Except in practice there is. One difference is that there is no need for a hack to detect the input type (touchscreen vs. mouse).
Another is that `libinput` supports calibration matrices. It's not been needed for any in-tree devices, but an x86 tablet I own requires it (per-device though). While the support isn't in Mobile NixOS yet, it should be possible to add handle this.
Additionally, working with libinput feels much better, as it does things like translate touchpad events to relative movements for you (me).
This is a big one! …
=> boot: A few updates to LVGUI

boot/init/lib/system.rb, devices/google-walleye/default.nix, devices/motorola-surfna/default.nix, devices/pine64-pinephone/default.nix, devices/razer-cheryl2/default.nix, devices/sony-pioneer/default.nix, devices/xiaomi-begonia/default.nix, devices/xiaomi-lavender/default.nix, examples/hello/configuration.nix, examples/target-disk-mode/configuration.nix, modules/adb.nix, modules/initrd.nix, modules/stage-1/tasks/usb-gadget-task.rb
It happens that, with time, I learned enough to finally be able to tackle this problem.
With these changes, `adb` in stage-1 (and I expect the system) works with GadgetFS devices:
While it doesn't seem needed, after all we have `rndis` working just fine, it is. See, sometimes `rndis` is a big unknown variable that is hard to correctly *guess* the proper solution for. With these changes you can get insight into the device using `adb`, and gather the required knowledge to setup `rndis`, if desired. 
Cannot test on, due to hardware issues:
=> Enable ADB with GadgetFS devices

devices/google-marlin/default.nix, devices/google-marlin/firmware/default.nix
Tested working fine on my Pixel XL (`google-marlin`).
Fetching the firmware from the upstream factory image ended up being most convenient, and is my personal preference.
=> Enable WiFi for google-marlin

overlay/mobile-nixos/kernel/builder.nix
Using string interpolation for concatenating paths caused the whole nixpkgs source to be included as an `inputSrc` for the kernel derivation.
**linux.drv:**
```json
"inputSrcs": [
"...",
"/nix/store/4crmmrpb9axxymrrh77lf35n015scnpj-mobile-nixos",
"...",
],
```
_I have my mobile-nixos worktree of nixpkgs under `nixpkgs/mobile-nixos`, which is why the above is named `mobile-nixos`._
With concatenation, only the resulting file is included as an `inputSrc`, which avoids unnecessary kernel rebuilds when nixpkgs changes.
**linux.drv:**
```json
"inputSrcs": [
"...",
"/nix/store/hdr6v584ig3dpjlcs9afxxky3lvzm2nw-randstruct-provide-seed.patch",
"...",
],
```
=> kernel-builder: Avoid string interpolation for path concatenation

overlay/mobile-nixos/kernel/builder.nix
This continues the fixes in commit d14b99e for the changes introduced in nixpkgs#110544.
=> kernel-builder: Fix detecting dtb support (after nixpkgs#110544)

modules/stage-1/tasks/usb-gadget-task.rb
`#constantize` does not exist on `String`.
This would only have been an issue in the improbable cause that a daemon
is not configured for an FFS gadget.
=> stage-1/usb-gadget: Fix error message error

boot/init/tasks/switch_root.rb, boot/recovery-menu/main.rb, devices/pine64-pinephone/default.nix, modules/initrd.nix, modules/module-list.nix, modules/stage-0.nix, modules/system-build.nix, overlay/mobile-nixos/fdt-forward/default.nix, overlay/mobile-nixos/fdt-forward/fdt-forward.sh, overlay/mobile-nixos/map-dtbs/default.nix, overlay/mobile-nixos/map-dtbs/map-dtbs.sh, overlay/overlay.nix, overlay/u-boot/0001-mobile-nixos-work-around-ubootTools-cross-compilatio.patch, shell.nix
We were left with the following issues to deal with:
- Fixes #264 
- Fixes #266
This PR implements both features.
* * *
It is possible to continue booting with the kernel used to boot the stage-0 bootloader. It will be useful for the three following scenarios:
- Validating kexec did not cause an issue with the booted system
- Recovering a system where none of the generation kernels boot properly
- Testing a kernel build without making a generation
* * *
Self-explanatory... Or is it?
Each generation could have their own DTB, sometimes with fixes. Re-installing the bootloader to use the fresher DTB is not really a nice thing to have to do.
This change makes it so the call to `kexec` uses the `--dtb` flag.
But wait, there's more!
The kernel assumes some entries will be added to the FDT …
=> Finish stage-0 boot features

doc/_support/converter/lib/processor/page.rb, doc/default.nix
The online site wasn't built with the same environment as used for development.
I assume `/build/doc` vs`/tmp/nix-build-mobile-nixos-docs.drv-0/doc/` comes from the possible lack of sandboxing.
Anyway, the fix is to actually strip the right thing, and not an arbitrary hardcoded value.
Additionaly, scan the output for presence of NIX_BUILD_TOP, to make sure it won't happen again!
=> doc: Fix issue with build dir references

boot/init/tasks/udev.rb
In some instances, e.g. really slow CPU, udev might not have run, and
libinput will not be able to work appropriately.
That is because uevent files will be missing.
=> boot/init: Make udev a dependency for the switch root target

boot/script-loader/mruby-lvgui-native-fragment/lvgui.nix, examples/demo/configuration.nix, modules/quirks/framebuffer.nix
This is an implementation detail PR.
Some platforms, though it looks like all android-first platforms, requires the framebuffer driver to be "told" to update the display. This is done through the `FBIOPAN_DISPLAY` `ioctl`.
The updated `lvgui` release does it for fbdev. This is not needed for DRM.
It is, at worst, a no-op on other tested platforms.
This may break some setups. Previously `msm-fb-refresher` from stage-1 was **not** killed when switching root. This means that stage-2 X11 may be working only when it was started in stage-1.
This is why `examples/demo` is now starting it unconditionally. Previous rootfs images, if not re-configured, will have a slight breakage with fresh boot images.
=> lvgui: "pan" framebuffers

release.nix
This includes the whole `tested` job (a simple no-op for hydra), but
adds additional things we want to track success for.
`tested` is for the basic minimum we want to succeed.
`testedPlus` adds more exotic, and less well-tested platforms.
=> release.nix: Add testedPlus aggregate job

bin/hydra-eval, release.nix
This helper is intended to be used by contributors that are changing
parts of this project that are either touching `lib/` and the evaluation
helpers, or changing `release.nix`.
There are no facilities to *compare* evals, yet. But this can be done by
the contributor, they can go to any commit they want to compare to, run
the eval and save the output markdown report. Then they can compare
against their new markdown report.
Finally, splitting the eval errors like we do in the reports should make
it really obvious what errors happened during the eval.
Here's what it looks like:
* [With the current tip of master](https://gist.github.com/d2e9a47de833f166af2f9a58d1bc513e)
* ~~[With this PR](https://gist.github.com/5cb881527738a8651387ec8258fd8a86)~~
And oh, look, the fix is not actually right! …
=> bin/hydra-eval: Add hydra-like eval helper

overlay/mobile-nixos/android-flashable-zip/make-flashable-zip.nix
This was broken in a hastily done rebase :/
=> overlay: Add missing `make-flashable-zip`.

devices/pine64-pinephone/README.adoc
Hi @samueldr,
as discussed on IRC, this updates the pinephone README to refer to the boo partition as mmcblkXp3.
Thanks!
=> pinephone: Update boot partition name in README

modules/cross-workarounds.nix, overlay/mobile-nixos/cross-canary/test.nix, overlay/mruby-builder/mruby/default.nix, overlay/overlay.nix, release.nix
This is intended for CI (Hydra).
It should, hopefully, make it obvious if binaries produced do not work.
Right now it's testing a really shallow subset of things, but I'm not even sure it is ever going to catch anything anyway.
Let's see what will happen
Issues on `amazon-austin` could not be reproduced on the latest Nixpkgs revisions. I assume it was specific to something that was fixed in-between the last known good, and the current-soon-good.
It was tested good using:
https://github.com/samueldr/nixpkgs/tree/wip/armv7lfixes
~~(Depends on #316)~~
=> cross-canary: Execute cross-built binaries using qemu-user

overlay/mobile-nixos/autoport/default.nix
Mainly fixes issue with the original host being taken down. (For
unrelated reasons.)
=> autoport: 0.0.1 -> 0.0.2

overlay/dtbtool-exynos/default.nix, overlay/mkbootimg/default.nix
Not sure if making a patch would be better, or what the preference is. I can confirm that both tools now at least build with `nix-build --argstr device pine64-pinephone pkgs.<pkg-name>`.
I don't know if this is useful for anything, but since it's in hydra I guess it might be useful for something.
A nice step towards a more green hydra :).
=> dtbTool-exynos + mkbootimg: support cross-compilation

devices/pine64-pinephone/default.nix, devices/pine64-pinephone/sound.nix, devices/pine64-pinephone/ucm2/PinePhone/HiFi.conf, devices/pine64-pinephone/ucm2/PinePhone/PinePhone.conf, devices/pine64-pinephone/ucm2/PinePhone/VoiceCall.conf, devices/pine64-pinephone/ucm2/ucm.conf
thanks to @zhaofengli for showing how to make it work in #331
=> pine64-pinephone: add alsa ucm config files to make the audio work

modules/lib.nix
fixes #353
Allows hosts to make use of specialArgs if they are using a new enough version of nixpkgs and lib/evalModules. Specifically the change from nixos/nixpkgs#121870 is needed. I don't think there is any way to fix this problem for people using older versions.
=> module/lib: try to pass specialArgs to eval

examples/demo/configuration.nix, examples/demo/workaround-v4l_id-hang.nix
This fixes:
- The currently broken build
- Uses the now-known workaround for the hang on boot
The main goal here is to get the demo rootfs to be built again on Hydra.
=> examples/demo: Misc fixes

devices/google-marlin/default.nix
When the ttyHSL0 console isn't actually available, things will hopelessly break.
I also took the time to cleanup the (now known to be) unneeded kernel params.
Actually tested on `google-sailfish`, but turns out the build works.
cc @danielfullmer 
cc @nh2
=> Fix boot problem with google-marlin/sailfish

modules/lib.nix
#354 doesn't really work because `args` is shadowed by the inner definition on line 19. Tested to work with Colmena which relies on `specialArgs` for evaluation.
cc @Pacman99
=> module/lib: Actually pass specialArgs to eval

overlay/mobile-nixos/kernel/builder.nix
In addition, review the implementation so it's easier to ignore tokens.
Fixes #330
=> kernel-builder: Add additional ignored tokens for normalized config

modules/system-types/uefi/default.nix
While this, in theory, should help with a theoretical uefi-aarch64
target, in practice there are other issues to be investigated.
It *looks* like `objcopy` as built for aarch64-linux, native and cross
does not understand the UEFI PE executable format.
=> system-types/uefi: Use proper prefix for objcopy

boot/script-loader/mruby-lvgui-native-fragment/lvgui.nix, overlay/mruby-builder/mruby/default.nix
This fixes the issues with rendering SVGs when a dimension is bigger than 2048
Also a minor fix for mruby's maintainer. The previous value came from importing the NixOS derivation.
=> lvgui: 2021-07-19 -> 2021-07-20

devices/pine64-pinephone/overlay/crust-firmware/default.nix
Tested to boot with `build.disk-image` built with:
* https://github.com/NixOS/mobile-nixos/pull/378
* https://github.com/NixOS/mobile-nixos/pull/376
=> pine64-pinephone: upgrade crust to 0.4

devices/pine64-pinephone/u-boot/default.nix
Tested to boot with `build.disk-image` built with:
* https://github.com/NixOS/mobile-nixos/pull/377
* https://github.com/NixOS/mobile-nixos/pull/376
=> pine64-pinephone: upgrade arm-trusted-firmware to 2.5

devices/pine64-pinephone/modem.nix
Taken from https://github.com/NixOS/mobile-nixos/pull/347/
Motivation: Fix modem on postmarketOS edition PinePhone.
eg25-manager is being considered in https://github.com/NixOS/mobile-nixos/issues/348. Even if we want that, we would need a kernel patch.
Until then, let's fix modems on the other PinePhones.
For the postmarketOS edition PinePhone, the device path is:
```
sys-devices-platform-soc-1c1b000.usb-usb2-2\\x2d1-2\\x2d1:1.4-net-wwan0.device
```
=> pine64-pinephone: Use the more generic device path for modem

devices/pine64-pinephone/firmware/default.nix
Documented at https://xnux.eu/devices/feature/anx7688.html
Example dmesg of this working:
```
$ dmesg | grep anx7688
[    3.200922] anx7688 1-0028: power enabled
[    3.201218] anx7688 1-0028: Vendor id 0x1f29
[    3.216944] anx7688 1-0028: power disabled
[    3.217173] anx7688 1-0028: enabling USB BC 1.2 detection
[    3.217337] anx7688 1-0028: plug irq (cd=1)
[    3.237870] anx7688 1-0028: BC 1.2 result: SDP
[    3.237893] anx7688 1-0028: cable inserted
[    3.280929] anx7688 1-0028: power enabled
[    3.353049] anx7688 1-0028: eeprom0 = 0x03
[    3.353080] anx7688 1-0028: fw loaded after 40 ms
[    3.353267] anx7688 1-0028: OCM firmware loaded (version 0x2410)
[    3.354327] anx7688 1-0028: send pd packet cmd=0x00 05 00 32 90 01 26 12
[    3.394021] anx7688 1-0028: send pd packet …
```
=> pine64-pinephone: include USB-C port anx7688 firmware

devices/pine64-pinephone/kernel/default.nix
With a patch that we should get mainlined.
* * *
Verified to allocate CMA correctly:
```
Jul 26 20:23:24 itchy kernel: Reserved memory: created CMA memory pool at 0x00000000b8000000, size 128 MiB
```
For some reason megapixels only shows a black screen for me. BUT, before this change it would Abort, while with this it continues running. I wonder if running on X11 or non-phosh is supposed to work.
```
Failed to get display configuration: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Name "org.gnome.Mutter.DisplayConfig" does not exist
```
To *correctly* test, `cma=` **should not** be part of the kernel command-line arguments.
cc @Thra11 @zhaofengli @tomfitzhenry
Closes #201
=> pine64-pinephone: Increase CMA to 128MiB

lib/image-builder/makeFilesystem.nix
fixes https://github.com/NixOS/mobile-nixos/issues/372
Per https://github.com/NixOS/mobile-nixos/issues/372, I observed
building an image takes ~40 minutes, and it spends the vast majority
of that performing `du` on the files that will be included in the image.
Most of that time is on process invocation overhead, and thus we can
save a lot by batching calls to `du`.
Per https://danielmiessler.com/blog/linux-xargs-vs-exec/, replacing
`find -exec du` with `find -print0 | xargs -0 du` is an optimisation to do
this. xargs will invoke du as "du fn1 fn2 fn3 fn4 ...", etc.
Before: 44mins (full output: https://paste.debian.net/1203075/ )
After: 1m45s (full output: https://paste.debian.net/1203076/ )
To reproduce this issue on a smaller dataset, try the before and after
on a directory with many …
=> imageBuilder: speed up gen on binfmt by batching `du` calls: 44min -> 1min45s

devices/samsung-a5y17lte/default.nix, modules/system-types/android/default.nix, modules/system-types/android/flashable-zip.nix
Samsung devices seem to use uppercase partition names.
This follows the convention used for the system partition.
=> Fix android flashable zips for systems with differently named boot partitions

default.nix, doc/_support/devices/default.nix, doc/boot_process.adoc, doc/getting-started.adoc, examples/demo/default.nix, examples/hello/README.md, examples/hello/default.nix, examples/target-disk-mode/README.md, examples/target-disk-mode/default.nix, lib/eval-with-configuration.nix, modules/devices-metadata.nix, modules/generated-filesystems.nix, modules/initrd-logs.nix, modules/initrd.nix, modules/module-list.nix, modules/outputs.nix, modules/recovery.nix, modules/stage-0.nix, modules/system-types.nix, modules/system-types/android/default.nix, modules/system-types/android/flashable-zip.nix, modules/system-types/depthcharge/default.nix, modules/system-types/depthcharge/device-notes.adoc.erb, modules/system-types/u-boot/default.nix, modules/system-types/uefi/default.nix, modules/system-types/uefi/device-notes.adoc.erb, modules/system-types/uefi/vm.nix, release.nix
`system.build` is, at best, a wart in the current design of the NixOS options. It is an arbitrary attrset full of arbitrary under-defined values. This, in itself, eh, is an implementation detail.
The issue is that Mobile NixOS started with using that catch-all property to transmit internal *and* user-centric outputs. Now, *that* is a problem. First, we have to dance around any possible names used by NixOS, as it's *just* an attrset, without `mkForce` and similar merge semantics.
The solution here, and probably should be investigated by NixOS to provide better composition semantics, is to provide all outputs as discrete options in the options system. Internal-use ones are marked `internal`.
> Side-note: It has been implemented under the `mobile.outputs` namespace, but that's not the only …
=> Use mobile.outputs rather than system.build

overlay/overlay.nix, pkgs.nix
Fix ubootTools by not applying the already upstreamed patch anymore.
Update nixpkgs pin to a more recent version that seems ok-ish.
Fixes https://github.com/NixOS/mobile-nixos/issues/421.
=> Fix uboottools, update nixpkgs pin

overlay/mobile-nixos/kernel/builder.nix
Recent updates in nixpkgs unstable (after the current pin) will cause a change in the `as` version. This patch prevents this from affecting any kernel builds,
=> overlay/kernel-builder: ignore changes to CONFIG_AS_VERSION

pkgs.nix
This would have been needed with the lvgui/libinput fixes.
Better late than never.
* * *
> But how did I decide of the revision to use?
Simple! I looked [at the hydra jobset](https://hydra.nixos.org/jobset/mobile-nixos/unstable) and chose a *generally successful* recent build.
- https://hydra.nixos.org/eval/1727289
In the *Inputs* tab you can see the revisions used.
=> pkgs.nix: Update pin to 6daa4a5c045d40e6eae60a3b6e427e8700f1c07f

.ci/instantiate-all.nix, release.nix
This does **not** add more work. This only adds more tracking. The kernels as used here *are already part of the builds*.
By making them discrete components of the eval, we are now able to better track kernel build issues.
Fixes #434
=> release.nix: Add kernels to the jobset

default.nix
This preserves location information, e.g. in the `nixos-option` tool
or in errors about duplicate option definitions.
=> default: refer to local.nix directly

examples/demo/configuration.nix, modules/initrd-boot-gui.nix
Recently nixos-unstable made accessing `pkgs.xlibs` a throw. I didn't see any other instances of this in a ripgrep, but this is just a nieve search-replace in my editor for the matching file that actually access it in my search.
=> all: xlibs -> xorg

modules/system-target.nix, modules/system-types/u-boot/default.nix, modules/system-types/uefi/default.nix, modules/system-types/uefi/vm.nix
The preferred way to refer to these is via stdenv.*Platform.
These will eventually be aliases in upstream Nixpkgs.
=> treewide: remove references to toplevel platform attrs

overlay/mobile-nixos/kernel/builder.nix
These are used in nixpkgs to check for firmware compression support since https://github.com/NixOS/nixpkgs/commit/8aa8e0ce7f137fe329608efcbb3494a5e6a63f42 and is expected in other out-of-tree kernel modules too.
Fixes https://github.com/NixOS/nixpkgs/issues/173832.
=> overlay/kernel-builder: Implement kernelOlder/kernelAtLeast

examples/hello/configuration.nix, modules/cross-workarounds.nix, modules/system-types/uefi/default.nix, pkgs.nix
Look, no workarounds on 64 bit!
Tested:
- Running the UEFI VM on x86_64
- Running AArch64 `xiaomi-lavender` (`examples/hello`)
- Running armv7l `amazon-austin` (`examples/hello`)
- Building the pinephone image (assumed to run fine)
=> Update Nixpkgs pin (and fixes for recent updates)

examples/phosh/README.md, examples/phosh/configuration.nix, examples/phosh/default.nix
This provides a Phosh example, that supports GSM.
Tested by:
```
$ NIX_PATH=~/src/nixpkgs       # that contains https://github.com/NixOS/nixpkgs/pull/153940
$ NIXPKGS_ALLOW_UNFREE=1 nix-build examples/phosh --system aarch64-linux --argstr device pine64-pinephone -A outputs.default
```
This image boots on a Pinephone to Phosh, can receive calls, and can connect to 4G.
Inspired by https://github.com/NixOS/mobile-nixos/pull/352, this PR is simpler, following subsequent upstreaming:
* https://github.com/NixOS/nixpkgs/pull/153940
* https://github.com/torvalds/linux/commit/d900a1cd310de097fb94796ca575c118b2637b3b
* Removal of Android related directives.
=> examples/phosh: init

overlay/mobile-nixos/kernel/builder.nix, overlay/mobile-nixos/kernel/eval-config.nix
This works around an issue where, with a large set of config options, it would error out like so:
```
ErroSysError{executing '/nix/store/eee-bash-5.1-p16/bin/bash': Argument list too long
error: builder for '/nix/store/eee-linux-aarch64-unknown-linux-gnu-5.17.5.drv' failed with exit code 1;
```
=> Fix kernel config validation with large amount of options

modules/system-types/u-boot/default.nix
devnum was already provided from the distro bootcmd. Furthermore,
mmc_bootdev is an allwinnerism.
* * *
This is a *correctness* fix. This will be needed for Pinephone Pro support (and support any other U-Boot platform).
=> system-types/u-boot: Fix build for non-allwinner

modules/initrd-kernel.nix
Follow-up to #478
See https://github.com/NixOS/nixpkgs/commit/8aa8e0ce7f137fe329608efcbb3494a5e6a63f42
=> initrd-kernel: Fix regression with generic rootfs

examples/demo/configuration.nix, modules/boot-initrd.nix
This is unused because the underlying logic has been removed.
=> stage-1: remove initFramebuffer option

modules/system-types/depthcharge/depthcharge-build.nix
I don't actually own this device, but maybe someone will find this helpful. Filed upstream PR here: https://github.com/thefloweringash/kevin-nix/pull/4
=> asus-dumo: fix make-kernel-its for recent makeimage

boot/lib/lvgui/lvgui/windows.rb
generation-switch in recovery-menu kept crashing.
this fixes it ;)
cc @samueldr
=> lvgui: Fix add_switch description regression

overlay/mobile-nixos/lvgui/default.nix
adds option to compile with debug-information included.
cc @samueldr
=> mobile-nixos/lvgui: mkLVGUIApp add enableDebugInformation option

examples/hello/app/windows/device_information.rb, examples/hello/app/windows/main.rb
This shows useful information by guessing at the ambiant system.
But why? So we can have more interesting screenshots with the hello app.
Here's an example of the simulator app on my Steam Deck:
<details><summary>Unfold for picture</summary>
</details>
The main issue right now with it, and is unsolvable, is that on ARM CPU information is generally *bad*. E.g. you'll see Cortex-A53, not Rockchip RK3399. There is no way I could see to get the information in a reliable manner.
A slight issue, also unsolvable AFAICT, is that we can't really get the actual memory size (e.g. 64GiB for 64GiB), we always get *some other number*. Which is why I left it to the MiB scale, makes some amounts less annoying to deal with.
Note that testing with the simulator *in practice* provides the exact same …
=> hello: Add basic device info window

overlay/mobile-nixos/kernel/builder.nix
In linux commit f91e46b1a722 (~ 5.12) the makefile rules for
{menu,n,g,x,}config were unified using a make definition,
which involved doubling the dollar sign from `$<` to `$$<`.
This broke a piece of sed magic in the kernel builder.
=> unbreak bin/menuconfig on kernel sources > 5.12

overlay/mobile-nixos/kernel/builder.nix, overlay/mobile-nixos/kernel/gcc10-extern_YYLOC_global_declaration.patch
This is causing a chunk of the failures in the Mobile NixOS hydra evals. And it's also causing the failure on `tested`.
Let's get those green!
=> kernel-builder: Fix older kernel build with -fno-common

overlay/mobile-nixos/kernel/builder.nix
From #506, by @telent.
Let's fast-track this change to (slightly) reduce the scope of that other PR.
* * *
add parens to enable modules_install when isModular
in nix 2.10.3,
```
nix-repl> if true then [ 10] else [8] ++ [4]
[ 10 ]
nix-repl> (if true then [ 10] else [8]) ++ [4]
[ 10 4 ]
```
=> kernel-builder: Fix modules_install invocation

doc/_support/styles/layout.less
Also change the default background to fix a slight bug with the #333 "overspill" background only showing up on the first "viewport" height.
=> docs: Fix layout for wide displays

boot/init/tasks/switch_root.rb
In #300 I "fixed" stage-0 by adding a switch to toggle between it being
enabled and disabled in the recovery menu. *That* works as expected.
In 2a46962d7638f0120db4678a97e8dc87ed45d0c9 one can observe that the
`#will_kexec?` method will use data that will only come from the
`choice` made from the recovery interface. The `@use_generation_kernel`
member is not set at any other point.
With ruby semantics, this means that the `if` is false, so *unless* you
choose to boot using the recovery menu, it will never trigger `kexec`.
Why has this gone through this way? Most likely because my main testing
target was configured so it *always* went to the recovery menu at the
time, meaning that I never saw the default behaviour.
* * *
* * *
cc @betaboon, note that this will not fix the other problem you …
=> init: Fix kexec condition in SwitchRoot

lib/image-builder/makeExt4.nix
Let's ensure we have enough inodes. Twice the amount needed should be fine, right?
=> image-builder/makeExt4: Fix inodes exhaustion

examples/phosh/configuration.nix, examples/phosh/phosh.nix
Racing changes in preparation for #522.
As described in its commit, the `examples/phosh/phosh.nix` file is public API and can be imported in a user's configuration to have some good defaults for Phosh.
=> phosh: prepare for installer

boot/init/tasks/auto_resize.rb
This way this time-consuming step is guaranteed to be properly shown to the end-user.
=> boot/init: Autoresize wait for graphics

devices/pine64-pinephone/default.nix, devices/uefi-x86_64/default.nix, examples/phosh/phosh.nix, modules/beautification.nix, modules/module-list.nix, modules/plymouth.nix
This build on top of #523, since it enables it for phosh.
~~I tested against qemu and against `google-blueline`, but in both cases while the service started fine, it didn't seen to work as expected :/.~~ [It needs the boot image to be reflashed since it relies on a kernel command-line parameter](https://github.com/NixOS/nixpkgs/blob/f634d427b0224a5f531ea5aa10c3960ba6ec5f0f/nixos/modules/system/boot/plymouth.nix#L125).
=> modules/beautification: Start adding fluff with silent/splash boot

modules/adb.nix, modules/module-list.nix, modules/usb-gadget.nix, overlay/gt/default.nix, overlay/libusbgx/default.nix, overlay/overlay.nix
From https://github.com/NixOS/mobile-nixos/pull/506, by @telent.
Let's reduce the scope of that other PR. This change requires a tiny bit more testing, and slight cleaning.
I have kept authorship as-it-was, but split the change into logical units. This will need further cleanup.
The TODO items in the `adb` module could be handled in this PR, but not doing so wouldn't be a regression.
* * *
the problem we are trying to solve is that when adbd is started in stage-1, it does not survive to stage-2. This is due to two things
- the config in configfs becomes disabled ("UDC" file becomes empty)
- adbd process is killed
This is more a workaround than a resolution: perhaps the better approach would be for stage-1 to clean up its configfs properly, and then write a NixOS module for adbd, which …
=> Add gadgetfs support for adb in stage-2

boot/init/tasks/modules.rb, boot/init/tasks/switch_root.rb
Most of these from #511.
* * *
- `Tasks::SwitchRoot` with stage-0 would fail if the selection menu wasn't used.
- On a limited set of android devices, a bogus `init=` parameter may be provided, skip it.
- Log how the generation was selected
- Be more resilient against non-modular kernels
=> boot: fix misc issues

modules/initrd.nix
The updated `ncdu` is built in a way that makes it fail on older CPUs.
=> initrd: Use ncdu_1 for now

modules/quirks/audio.nix, modules/quirks/default.nix
Provides a general way to add ALSA UCM profiles for a device.
Tested with pinephone pro on my [wip/pinephone-pro](https://github.com/wentam/mobile-nixos/tree/wip/pinephone-pro) branch, both pulseaudio and pipewire working.
This is set up to overlay files onto pkgs.alsa-ucm-conf to accomodate [profiles distributed like this](https://gitlab.com/pine64-org/pine64-alsa-ucm). These have references to the main alsa-ucm-conf repo but are distributed out of that context.
This does mean UCM derivations need to follow the structure of the alsa-ucm-conf repo (and not provide their own ucm.conf top-level file).
A device can just do something like:
```nix
{
mobile.quirks.audio.alsa-ucm-meld = true;
environment.systemPackages = [ pine64-alsa-ucm ];
}
```
Using the term 'meld' rather than 'overlay' to …
=> quirks/audio: add quirk for custom UCM profiles

modules/initrd.nix
This fixes systemd-boot menu entry generation.
=> initrd: generate a more compatible noop initrd secret appender

boot/init/default.nix, boot/init/init.rb
Otherwise it's a real pain to debug.
The backtrace is shown even on the display!
Note that the backtrace entries for mruby-native bits won't be available unless mruby itself is built with `debug` turned on. It shouldn't really cause any trouble though.
=> boot: Add backtraces in

modules/outputs.nix, release.nix
We don't need the actual "physical" images to be built.
What is really needed is that the built outputs are propagated.
Assuming I understood the underlying issue, this should fix #544.
=> release.nix: Use toplevel instead of rootfs

examples/phosh/phosh.nix
kgx is an alias of gnome-console in Nixpkgs, so switch to using gnome-console directly.
=> examples/phosh: rename kgx -> gnome-console

boot/script-loader/mruby-lvgui-native/lvgui.nix, boot/splash/default.nix, boot/splash/ui.rb
Under unclear conditions (understandably due to the source of the bug), the passphrase input could sometimes crash.
I reproduced relatively-reliably the issue under different conditions, and verified that the overflow fix from upstream fixes this problem.
@Mindavi if you can test, please do. ~~I will on my devices before merging.~~ Not that I was able to reliably make it crash, it doesn't seem to want to now.
* * *
This also fixes a visual issue with the stage-1 passphrase input, and how it wouldn't hide properly anymore.
=> Fix issues with passphrase input in stage-1

overlay/overlay.nix
Breaking change: https://github.com/NixOS/nixpkgs/pull/199912
* * *
Tested building
```
time nix-build examples/installer --argstr device lenovo-krane -A pkgs.xorg.xf86videofbdev
```
Against both current pin and current Nixpkgs, verified that the changes were being applied still correctly.
=> overlay: Fix eval after xorg improvements

examples/installer/app/lib/configuration.rb, examples/installer/pkgs/scripted-installer/automated-installer.rb, examples/installer/pkgs/scripted-installer/disk-formatter.rb, pkgs.nix, release.nix
Builds on top of #552.
This adds depthcharge knowledge to the installer.
* * *
=> installer: Add support for depthcharge

modules/quirks/audio.nix
This fixes the issue of ucm2 being not-linked due to missing starting slash. This wasn't noticed in default environments with phosh and KDE mobile, since they link the entire `/share`.
=> audio quirks: fix ucm2 symlink

bin/menuconfig, overlay/mobile-nixos/kernel/builder.nix
https://github.com/torvalds/linux/commit/d5ea4fece4508bf8e72b659cd22fa4840d8d61e5 changed the invocation, thus breaking our sed.
Let's make this more robust.
=> Fix bin/menuconfig

devices/families/sdm845-mainline/default.nix, devices/motorola-addison/default.nix, devices/motorola-potter/default.nix, devices/oneplus-oneplus3/default.nix, modules/mobile-device.nix
> I'm thinking we probably should enable adding `config.mobile.device.firmware` to `hardware.firmware` automatically by default, as it seems to be a common pain point among users.
> 
> The only reason I don't notice it myself is because the few devices I use with Mobile NixOS I use my "integrated" custom config where I do this outright.
> 
> (To be handled in a separate PR)
— https://github.com/NixOS/mobile-nixos/pull/535#issuecomment-1336268322
Now handled in a separate PR.
This will make it less surprising for end-users, as firmware that is needed will be provided by default.
=> Enable use of device firmware by default

examples/installer/modules/all.nix, examples/installer/modules/boot-closure.nix
As [mentioned here](https://github.com/NixOS/mobile-nixos/pull/565#discussion_r1083563692), move this into a discrete PR.
- Install on wormdingler, building the `kpart` was as fast as expected.
=> examples/installer: Add boot closure to installer

.ci/instantiate-all.nix, devices/amazon-austin/kernel/default.nix, devices/asus-dumo/firmware/default.nix, devices/asus-z00t/default.nix, devices/google-marlin/default.nix, devices/lenovo-krane/firmware/default.nix, devices/lenovo-wormdingler/firmware/default.nix, devices/oneplus-enchilada/firmware/default.nix, devices/pine64-pinephone/firmware/default.nix, devices/pine64-pinetab/firmware/default.nix, devices/samsung-a5y17lte/default.nix, modules/mobile-device.nix, overlay/dtbtool/default.nix
```
in job ‘examples.phosh.x86_64-linux.toplevel’:
error: The option `mobile.device.firmware' is used but not defined.
```
Also fixed other relevant breakage.
Tested using
```
$ nix-instantiate ./release.nix
```
=> Fix hydra eval issues that accumulated

devices/pine64-pinephone/kernel/config.aarch64, devices/pine64-pinephone/kernel/default.nix
I have used this kernel on my PinePhone for more than a day and haven't noticed any regressions. I tested the camera, 4G data connectivity, WiFi, waking from sleep, nheko, notifications and Firefox.
=> pine64-pinephone: kernel 6.0.10 -> 6.0.12

boot/lib/hal/recovery.rb, boot/lib/lvgui/lvgui/text_area.rb, boot/script-loader/mruby-lvgui-native/lvgui.nix, boot/splash/ui.rb
This is a combination of fixes that are relatively related.
First, when working on mainline for #496, it was found that the keypad is exposed as both a pointer and a keyboard, since mainline uses the mouse button bindings for the top two action buttons. This was a problem in lvgui, as it would assume only the pointer events were to be used, as its input system couldn't deal with an input device doing more than one thing at once. Furthermore, some more keyboard bindings were added for menu navigation.
- See https://github.com/mobile-nixos/lvgui/pull/10
The previous changes in lvgui ended-up confirming my assumption as to why some keyboard input wouldn't work. Some keyboards expose mouse functions! For example logitech unifying devices often expose both. So while fixing input with …
=> Fixes for boot GUI and physical keyboard/keypad

boot/init/tasks/switch_root.rb, boot/init/tasks/udev.rb
This fixes amdgpu suspend/resume on Steam Deck.
Unknown if it could fix anything else, but the same issue was not observed on any of intel, mali, panfrost, adreno.
Unclear how the stray `udevadm` was causing DRM issues on resume.
=> boot/init: Tear down udevd

boot/script-loader/mruby-lvgui-native/lvgui.nix
- https://github.com/mobile-nixos/lvgui/compare/62100c7b30a4abfd311dc2d8c503f5f253734a70..64d6c793be0cd71e9c665762934063e9c037125a
The important change is the DRM panel orientation property being read, and the panel being rotated (with bad-but-working software rotation).
- https://github.com/mobile-nixos/lvgui/pull/14
This change will affect only two in-tree devices, the `lenovo-wormdingler` and `lenovo-krane` devices. They have a panel orientation node on their panel, as the "native" orientation is portrait, but it is more likely to be used as landscape with the keyboard attachment.
This change was made mainly to target Steam Deck usage.
=> lvgui: 2023-02-25 -> 2023-03-02

boot/init/tasks/splash.rb, devices/uefi-x86_64/default.nix, modules/initrd-boot-gui.nix
This is useful for devices with USB, where input devices may take a short while before showing up.
With this, external USB keyboard passphrase input is reliable in the limited testing I did.
This change shouldn't cause any regressions as it *adds* a new behaviour, which is opt-in.
Note that the 2 seconds wait alone is likely sufficient on all tested targets. Though let's make this much more robust by ensuring we wait until things are settled for at least 2 seconds.
* * *
Why is this a quirk? That's mainly because it's the wrong, but trivial, way to work around the issue.
The proper solution will be to have the splash program, and thus lvgui, handle hot-plugged devices. It *is* possible to do, but not trivial. It will require some rework of its libinput driver. I have something else in the …
=> boot/init: Add a quirk to wait on USB devices to settle

boot/init/lib/mounting.rb, boot/init/tasks/luks.rb
Why only some? Because they're the ones I am confident in implementing.
Of those, many require hardware or a setup different enough that I'm not setup to test with:
- https://github.com/NixOS/mobile-nixos/blob/bf43312242f94eaf6356b58edfd837f15bef4bc8/boot/init/tasks/luks.rb#L39-L49
The only few I *could* implement, I don't really want to support at this time because they imply running *shell commands*, which may or may not work as expected compared to the upstream stage-1 sh script.
* * *
- Tested on `lenovo-wormdingler`, still boots... unsure how to correctly test TRIM.
- Actually boot with `bypassWorkqueues` just in case.
Quick visual check:
```
~ $ sudo cryptsetup status LUKS-FRANKGRIMES-ROOTFS 
[sudo] password for samuel: 
/dev/mapper/LUKS-FRANKGRIMES-ROOTFS is active and is in use. …
```
=> boot/init: Honor some cryptsetup arguments

overlay/mobile-nixos/kernel/builder.nix
This will solve a chunk of the still failing builds:
- https://hydra.nixos.org/eval/1792107#tabs-still-fail
The toolchain has been upgraded, and the kernel saves a bit more info about the toolchain, and makes a few more options available.
Normalizing the kernel configs would have worked to unclog hydra, but would be a backward-incompatible change. Even though we only support unstable and the pinned Nixpkgs, I don't like doing needless incompatible changes.
=> kernel/builder: Ignore more toolchain information in config

boot/lib/lvgui/lvgui/hal.rb
Some drivers may expose those without exposing capacity.
=> lvgui: use (charge now ÷ full) for battery as a fallback

modules/system-types/u-boot/default.nix
The whole attempt at settings bootargs would fail. Let's instead append until it can't fit.
This exact behaviour will depend on the exact U-Boot build. This was observed on a non-Mobile NixOS device, where I used Mobile NixOS to get an initial thing going.
* * *
What was done:
- Tested on out-of-tree device: PineNote
=> system-types/u-boot: Fix usage with long cmdline

devices/asus-dumo/default.nix, devices/families/sdm845-mainline/default.nix, devices/google-marlin/default.nix, devices/lenovo-krane/default.nix, devices/lenovo-wormdingler/default.nix, devices/pine64-pinephone/default.nix, devices/pine64-pinetab/default.nix, examples/hello/configuration.nix, modules/beautification.nix, modules/boot.nix, modules/module-list.nix, modules/system-types/uefi/vm.nix
This PR adds new semantics for managing the boot consoles.
Managing `console=` params manually is *foolish*.
With these options, we can set defaults by prefixing them, and more importantly, better control the order of our defaults.
This also adds *knowledge* about the serial console. This way enabling it is easier and universal.
* * *
What was done:
- Tested on Steam Deck (generic UEFI)
- Tested on `oneplus-enchilada`
- Verified with VM that serial feature works.
- Verified with `nix repl` that `config.boot.kernelParams` now strictly prefixes `console=` with our default configs.
=> Add options to better control console parameters 

modules/stage-0.nix
This ensures that, for implementation details, bits that use stage-0 as a synonym for stage-1 when it is not supported gets the same exact eval than the one for stage-1.
Without this change, some `fdt-forward` and changes made under that `mkIf` would end-up included. `fdt-forward` was found to be in the stage-1 image even though it was irrelevant.
=> modules/stage-0: Ensure enabling/disabling is a no-op

boot/lib/lvgui/lvgl/hacks.rb, boot/lib/lvgui/lvgui/progress_bar.rb, boot/script-loader/mruby-lvgui-native/lvgui.nix, boot/script-loader/mruby-lvgui-native/src/gem.c, boot/splash/configuration.rb, boot/splash/default.nix, boot/splash/ui.rb, modules/hardware-eink.nix, modules/initrd-boot-gui.nix, modules/module-list.nix
This adds a few options to improve use on eink displays.
The gist of it is these options ensures inverted "black on white" works. Up to and excluding later stage-2, this is verified to do a flicker-free black-on-white from the moment the kernel logo is shown.
I have tested this on the `pine64-pinenote` (PR pending) and the new VM with #612. Up until `cage` comes-up, the display sees no black updates; even a single frame will be rendered in my experience, and made obvious from the slow refresh. See https://github.com/mobile-nixos/lvgui/pull/17 for the fix for the one flicker we were in control of.
Relatedly, with the lvgui change we *should* be able, with some additional knowledge, to smoothly transition from the logo to the stage-1 progress, if it was desired. Including, but not limited, …
=> Add improved semantics for eink devices

modules/beautification.nix
I'm confused as to why nothing breaks anymore(?) without `mdDoc` being added, like it did a small while back.
=> modules/beautification: Add missing lib.mdDoc

modules/stage-0.nix
See, the `with` thing was totally making things hard to reason about!
Fixes regression from https://github.com/NixOS/mobile-nixos/pull/611
=> modules/stage-0: Fix fdt-forward ref

lib/eval-with-configuration.nix
This can be useful when used with `nix repl`. For example, using:
```
:p options.environment.systemPackages.definitionsWithLocations
```
You can figure out where a specific package was added, when simple grepping is hard in Nixpkgs.
=> eval-with-configuration: Expose options

modules/rootfs.nix
In some *off-label* use, I ended-up wanting to build a system without Nix built into the system.
This makes it possible. (Otherwise Nix would be brought in by this...)
As long as you don't intend to manipulate the Nix store in some form, not rehydrating is not an issue.
=> rootfs: Make rehydration optional

modules/initrd-kernel.nix, overlay/mobile-nixos/kernel/builder.nix
Fixes #624
* * *
What was done
- Tested on generic UEFI non-kernel-builder setup (no-op)
- Tested on `lenovo-wormdingler` with shared rootfs option enabled, and with kernel; fixes eval in both cases.
=> Fix eval with bootspec enabled

overlay/bootlogd/default.nix, pkgs.nix
Hardening flags were enabled in nixpkgs so bootlogd needs to be updated: https://github.com/mobile-nixos/bootlogd/pull/9
I update both of them simultaneously so that we don't build bootlogd without hardening. Also there is a deprecation warning with new nixpkgs:
```
trace: warning: literalExample is deprecated, use literalExpression instead, or use literalMD for a non-Nix description.
```
But I couldn't find where it comes from.
=> Update nixpkgs and bootlogd version.
