NixOS/mobile-nixos

- shell.nix
Added additional tools for porting devices.
> Added additional development tools

- boot/gui/main.rb
- boot/gui/simulator.nix
Additionally: fix cross-compiled simulator build.
* * *
This ensures we actually restore the console.
> boot/gui: Fix console restoring on exit

- devices/oneplus-oneplus3/README.adoc
Add documentation about flashing system image.
> oneplus-oneplus3: Document workaround for fastboot flash issue

- .ci/instantiate-all.nix
- release.nix
- systems/rootfs.nix
> Add hydra build product to the rootfs

- doc/getting-started.adoc
- lib/configuration.nix
Read the [added docs](https://github.com/NixOS/mobile-nixos/pull/123/files?short_path=56858fe#diff-56858feeaeccd0a0806f84f9f002f227)!
That should make it clear, otherwise I need to review this PR :).
* * *
Fixes #115
> Add a supported way to include from system configuration

- doc/_support/converter/lib/processor/page.rb
- doc/_support/news_article.erb
- doc/_support/styles/base.less
- doc/_support/styles/news.less
First, make an image-less article look proper.
Second, fix a weirdness with newlines and inline code elements.
> Misc. fixes for the site articles

- doc/_support/styles/base.less
It's only causing issues. It's not that big of a deal.
> Remove attempt at fixing spacing with inline code

- devices/asus-x018d/kernel/default.nix
Uh, woops!
https://hydra.nixos.org/build/123671200/nixlog/4
> asus-x018d: Fix hash

- overlay/mobile-nixos/autoport/default.nix
- overlay/overlay.nix
- shell.nix
This way the tool is exposed for all to enjoy.
> Provide autoport in the default shell

- bin/kernel-normalize-config
- bin/menuconfig
> Fix program name in usage messages

- boot/init/lib/task.rb
- boot/init/tasks/switch_root.rb
- boot/lib/hal/recovery.rb
- boot/splash/lib/ui.rb
- boot/splash/main.rb
This is more intended to show that the device will go into recovery once the boot is done... booting...
Though the boot is going so fast that the "Continuing" message, at least in QEMU, appears at the same time.
This will be more useful with less shallow systems, and real systems that are slower.
> stage-1: Acknowledge recovery boot mode

- doc/_support/styles/default.nix
> doc: Fix lessc maths breaking change

- doc/_support/all_news.erb
- doc/_support/converter/lib/processor/page.rb
- doc/_support/styles/theme.less
In addition, limit news items on front page to 10 items.
> doc: Add support for a news archive page

- .github/workflows/ci.yml
- boot/init/default.nix
- devices/pine64-pinephone/overlay/crust-firmware/default.nix
- devices/pine64-pinephone/overlay/qfirehose/default.nix
- doc/_support/converter/default.nix
- overlay/bootlogd/default.nix
- overlay/dtbtool-exynos/default.nix
- overlay/hardshutdown/default.nix
- overlay/make_ext4fs/default.nix
- overlay/mobile-nixos/kernel/builder.nix
- overlay/mruby-builder/mruby/default.nix
- overlay/ufdt-apply-overlay/default.nix
Deals with:
* `stdenv.lib` https://github.com/NixOS/nixpkgs/pull/111284
* `platform` having changed. https://github.com/NixOS/nixpkgs/pull/110544
> Fix misc. breakage from Nixpkgs changes

- lib/eval-with-configuration.nix
It was missing. The CI on this project didn't catch it.
> lib: Add missing eval-with-configuration.nix file

- examples/demo/configuration.nix
This was a late change, which *should* have been eval'd before hitting
merge :(.
> examples/demo: Fix rootfs eval

- boot/script-loader/mruby-lvgui-native/lvgui.nix
Addresses
- https://github.com/NixOS/mobile-nixos/pull/417#pullrequestreview-767028176
> lvgui: 2021-07-20 -> 2021-09-22

- boot/script-loader/mruby-lvgui-native/lvgui.nix
See: https://github.com/mobile-nixos/lvgui/pull/1
> lvgui: 2021-09-22 -> 2021-11-25

- devices/pine64-pinephone/u-boot/default.nix
- devices/pine64-pinetab/u-boot/default.nix
cc @zhaofengli 
This is the equivalent to #431.
Since U-Boot built, I have strong reasons to believe it will work.
> pine64-pinetab: u-boot: 2021.01 -> 2021.10

- modules/initrd-kernel.nix
- modules/shared-rootfs.nix
*sighs*...
So many things go wrong for using the "wrong" characters.
> generic images: Stop being fancy with filenames

- boot/script-loader/mruby-lvgui-native/lvgui.nix
See https://github.com/mobile-nixos/lvgui/pull/3
cc @betaboon
> lvgui: 2021-11-25 -> 2022-07-30

- boot/script-loader/mruby-lvgui-native/lvgui.nix
- overlay/mruby-builder/mrbgems/default.nix
Oops, I only had eval'd against the pinned Nixpkgs.
And also fix the bogus `licenses` field... accidental wrong completion from my IDE that's 99% sure.
> Fix last missed dropped alias

- modules/initrd-boot-gui.nix
Killing the GUI on my device causes a crash.
> initrd-boot-gui: add option to disable

- modules/module-list.nix
- modules/zram.nix
Racing changes in preparation for https://github.com/NixOS/mobile-nixos/pull/522.
> modules/zram: init with workarounds for zram

- pkgs.nix
- https://hydra.nixos.org/eval/1783397
> pkgs.nix: Sync to latest completed build

- boot/init/default.nix
- boot/lib/lvgui/lvgl/hacks.rb
- boot/lib/lvgui/lvgui/__init.rb
- boot/lib/lvgui/lvgui/_button.rb
- boot/lib/lvgui/lvgui/base_window.rb
- boot/lib/lvgui/lvgui/battery.rb
- boot/lib/lvgui/lvgui/clock.rb
- boot/lib/lvgui/lvgui/horizontal_separator.rb
- boot/lib/lvgui/lvgui/keyboard.rb
- boot/lib/lvgui/lvgui/option_selection.rb
- boot/lib/lvgui/lvgui/page.rb
- boot/lib/lvgui/lvgui/status_bar.rb
- boot/lib/lvgui/lvgui/text_area.rb
- boot/lib/lvgui/lvgui/windows.rb
- boot/script-loader/mruby-lvgui-native/lvgui.nix
- boot/script-loader/mruby-lvgui-native/src/debug.c
- boot/script-loader/mruby-lvgui-native/src/gem.c
- boot/splash/ui.rb
- examples/hello/app/windows/base_log.rb
- examples/hello/app/windows/lvguitesting.rb
- overlay/mobile-nixos/gui-assets/default.nix
- overlay/mruby-builder/mruby/builder.nix
Racing changes in preparation for https://github.com/NixOS/mobile-nixos/pull/522.
These changes are UI additions needed for the installer, and misc fixes.
New widgets and helpers. Though the main user-facing changes are the addition of a text input widget.
Why break this out? To make it easier on myself to self-review the changes.
> lvgui: Enhancements for the installer (and general QOL)

- examples/plasma-mobile/README.md
- examples/plasma-mobile/configuration.nix
- examples/plasma-mobile/default.nix
- examples/plasma-mobile/mobile-nixos-branding.nix
- examples/plasma-mobile/plasma-mobile.nix
- lib/image-builder/makeExt4.nix
- lib/image-builder/makeFAT32.nix
- modules/system-types/uefi/vm.nix
- pkgs.nix
- release.nix
~~This is WIP, and requires work still in a WIP branch for the Nixpkgs/NixOS side of things~~
Still requires some work to be merged, mainly regressions.
> examples/plasma-mobile-demo: init

- overlay/lib/extra-utils.nix
This fixes a regression in which binaries weren't stripped anymore.
See also: https://github.com/NixOS/nixpkgs/pull/185530
> extra-utils: Sync with Nixpkgs

- release.nix
> release.nix: Add lenovo-wormdingler installer build

- boot/script-loader/mruby-lvgui-native/lvgui.nix
See https://github.com/mobile-nixos/lvgui/pull/12
cc @Luflosi
> lvgui: 2023-02-11 -> 2023-02-25

- boot/script-loader/mruby-lvgui-native/lvgui.nix
Fixes issue with normal orientation displays and touch.
Tested on TP300LA; original PR at lvgui tested on pinephone too.
> lvgui: 2023-03-02 -> 2023-03-11

- CONTRIBUTING.adoc
- doc/in-depth/devices.adoc
> Fix documentation typo, and link in CONTRIBUTING.md

- modules/adb.nix
- modules/boot-control.nix
- modules/boot-initrd.nix
- modules/hardware-qualcomm.nix
- modules/hardware-ram.nix
- modules/hardware-rockchip.nix
- modules/hardware-screen.nix
- modules/initrd-base.nix
- modules/initrd-boot-gui.nix
- modules/initrd-fbterm.nix
- modules/initrd-logs.nix
- modules/initrd-network.nix
- modules/initrd-ssh.nix
- modules/initrd-usb.nix
- modules/quirks/framebuffer.nix
- modules/rootfs.nix
- modules/stage-0.nix
- modules/system-target.nix
- modules/system-types.nix
Only went through modules, since I ended-up changing some in another WIP branch.
There's still `with` in places that could be removed.
> modules: Remove needless with usage

- boot/init/lib/system.rb
- boot/init/tasks/symlink.rb
- modules/luks.nix
All details noticed when attempting to figure out #582.
No real theme to the change set.
* * *
What was done
- Tested on `oneplus-enchilada`
- Tested on Steam Deck (generic UEFI)
> boot: Misc. cleanups
